services:
  codingbrain_store:
    image: qdrant/qdrant:latest
    container_name: codingbrain-qdrant
    restart: unless-stopped
    ports:
      - "6433:6333"
    volumes:
      - codingbrain_storage:/qdrant/storage