#!/bin/bash
#
# Generate Docsify sidebar from all markdown files in the project
# Usage: ./scripts/generate-docs-sidebar.sh
#

set -e

PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUTPUT_FILE="$PROJECT_ROOT/docs/_sidebar.md"

echo "Generating sidebar from markdown files..."

# Start the sidebar file
cat > "$OUTPUT_FILE" << 'EOF'
<!-- Auto-generated by scripts/generate-docs-sidebar.sh -->
<!-- Run ./scripts/generate-docs-sidebar.sh to update -->

- [**Home**](/README.md)

EOF

# Function to create a nice title from filename
create_title() {
    local filename="$1"
    echo "$filename" | sed 's/\.md$//' | sed 's/[-_]/ /g' | sed 's/README/Overview/'
}

# Function to add section
add_section() {
    local label="$1"
    local path="$2"

    local files=$(find "$PROJECT_ROOT/$path" -maxdepth 1 -name "*.md" -type f ! -name "_sidebar.md" ! -name "index.html" 2>/dev/null | sort)

    if [ -n "$files" ]; then
        echo "" >> "$OUTPUT_FILE"
        echo "- **$label**" >> "$OUTPUT_FILE"

        echo "$files" | while read -r file; do
            if [ -n "$file" ]; then
                rel_path="${file#$PROJECT_ROOT/}"
                filename=$(basename "$file")
                title=$(create_title "$filename")
                echo "  - [$title](/$rel_path)" >> "$OUTPUT_FILE"
            fi
        done
    fi
}

# Add sections in order

# Root documentation
echo "" >> "$OUTPUT_FILE"
echo "- **Project Root**" >> "$OUTPUT_FILE"
for file in "$PROJECT_ROOT"/*.md; do
    if [ -f "$file" ]; then
        rel_path="${file#$PROJECT_ROOT/}"
        filename=$(basename "$file")
        title=$(create_title "$filename")
        echo "  - [$title](/$rel_path)" >> "$OUTPUT_FILE"
    fi
done

# Core docs
add_section "Documentation" "docs"

# Docs implementation
add_section "Implementation Docs" "docs/implementation"

# OpenMemory
add_section "OpenMemory" "openmemory"
add_section "OpenMemory API" "openmemory/api"

# Guidance files
echo "" >> "$OUTPUT_FILE"
echo "- **Guidance**" >> "$OUTPUT_FILE"
find "$PROJECT_ROOT/openmemory/api/app/guidance" -name "*.md" -type f 2>/dev/null | sort | while read -r file; do
    if [ -n "$file" ]; then
        rel_path="${file#$PROJECT_ROOT/}"
        filename=$(basename "$file")
        title=$(create_title "$filename")
        echo "  - [$title](/$rel_path)" >> "$OUTPUT_FILE"
    fi
done

# Embedchain
add_section "Embedchain" "embedchain"
add_section "Embedchain Docs" "embedchain/docs"

# Embedchain examples
echo "" >> "$OUTPUT_FILE"
echo "- **Embedchain Examples**" >> "$OUTPUT_FILE"
find "$PROJECT_ROOT/embedchain/examples" -name "*.md" -type f 2>/dev/null | sort | while read -r file; do
    if [ -n "$file" ]; then
        rel_path="${file#$PROJECT_ROOT/}"
        example_dir=$(dirname "$rel_path" | sed 's|embedchain/examples/||')
        filename=$(basename "$file")
        if [ "$filename" = "README.md" ]; then
            title="$example_dir"
        else
            title=$(create_title "$filename")
        fi
        echo "  - [$title](/$rel_path)" >> "$OUTPUT_FILE"
    fi
done

# Other sections
add_section "Mem0 TypeScript" "mem0-ts"
add_section "Mem0 TS OSS" "mem0-ts/src/oss"
add_section "Evaluation" "evaluation"
add_section "Examples" "examples"
add_section "Server" "server"
add_section "Vercel AI SDK" "vercel-ai-sdk"

echo ""
echo "Sidebar generated: $OUTPUT_FILE"
echo ""
echo "To preview documentation, run:"
echo "  cd $PROJECT_ROOT && python -m http.server 3000"
echo "  Then open http://localhost:3000/docs/"
